#!/bin/zsh
#
# Ubuntu env bootstrap
#
if ! command -v rcup &> /dev/null; then
  sudo apt-get update -y
  sudo apt-get install rcm -y
fi

if ! command -v starship &> /dev/null; then
  sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes
fi

if ! command -v tree &> /dev/null; then
  sudo apt-get install -y tree
fi

if ! command -v fd-find &> /dev/null; then
  sudo apt-get install -y fd-find
  mkdir -p ~/.local/bin
  ln -s $(which fdfind) ~/.local/bin/fd
fi

if ! command -v batcat &> /dev/null; then
  sudo apt-get install -y bat
fi

if ! command -v rg &> /dev/null; then
  sudo apt-get install -y -o Dpkg::Options::="--force-overwrite" ripgrep
fi

if ! command -v fzf &> /dev/null; then
  sudo apt-get install -y fzf
fi

if ! command -v direnv &> /dev/null; then
  sudo apt-get install -y direnv
fi

if ! command -v delta &> /dev/null; then
  wget https://github.com/dandavison/delta/releases/download/0.11.3/git-delta_0.11.3_amd64.deb
  sudo dpkg -i git-delta_0.11.3_amd64.deb
  rm git-delta_0.11.3_amd64.deb
fi

if ! command -v exa &> /dev/null; then
  sudo apt install -y exa
fi

sudo apt install -y fonts-firacode

[ ! -d '~/.local.gitconfig' ] && mv ~/.gitconfig ~/.local.gitconfig

rcup -d ~/dotfiles -x zshrc -x Brewfile -x vanilla-vim -x karabiner.json -x README.md

echo "source ~/dotfiles/zshrc" >> ~/.zshrc

source ~/.zshrc

[ ! -d '~/.config/base16-shell' ] && git clone --quiet https://github.com/tinted-theming/base16-shell ~/.config/base16-shell

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

nvim --headless +PlugInstall +qall
