#!/bin/zsh
#
# Ubuntu env bootstrap
#
if ! command -v rcup &> /dev/null; then
  sudo apt-get update -y
  sudo apt-get install rcm -y
fi

if ! command -v starship &> /dev/null; then
  sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes
fi

if ! command -v tree &> /dev/null; then
  sudo apt-get install -y tree
fi

if ! command -v batcat &> /dev/null; then
  sudo apt-get install -y bat
fi

if ! command -v rg &> /dev/null; then
  sudo apt-get install -y -o Dpkg::Options::="--force-overwrite" ripgrep
fi

if ! command -v fzf &> /dev/null; then
  sudo apt-get install -y fzf
fi

if ! command -v direnv &> /dev/null; then
  sudo apt-get install -y direnv
fi

if ! command -v delta &> /dev/null; then
  wget https://github.com/dandavison/delta/releases/download/0.11.3/git-delta_0.11.3_amd64.deb
  sudo dpkg -i git-delta_0.11.3_amd64.deb
  rm git-delta_0.11.3_amd64.deb
fi

if ! command -v exa &> /dev/null; then
  wget https://github.com/ogham/exa/releases/download/v0.10.0/exa-linux-x86_64-v0.10.0.zip
  unzip exa-linux-x86_64-v0.10.0.zip -d exa-tmp
  cd exa-tmp
  sudo mv bin/exa /usr/local/bin
  sudo mv completions/exa.zsh /usr/local/share/zsh/site-functions
  sudo mv man/exa.1 /usr/share/man/man1
  cd ..
  rm -rf exa-linux-x86_64-v0.10.0.zip exa-tmp
fi

sudo apt install -y fonts-firacode

[ ! -d '~/.local.gitconfig' ] && mv ~/.gitconfig ~/.local.gitconfig

rcup -d ~/dotfiles -x zshrc -x Brewfile -x vanilla-vim -x karabiner.json -x README.md

echo "source ~/dotfiles/zshrc" >> ~/.zshrc

source ~/.zshrc

[ ! -d '~/.config/base16-shell' ] && git clone --quiet https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

nvim --headless +PlugInstall +qall
